### ISSUE TITLE
Deactivating the Dashboard

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#10]
Hi

I am trying to create a list of properties from a child item in a dashboard. When I click add widget, 

> application.min.js:10 Cannot compile directive. Directive name is missing

When I choose grid and select values from item, there is a parent missing id though.
![screenshot 2016-11-23 19 17 58](https://cloud.githubusercontent.com/assets/515180/20575534/9c144208-b1b1-11e6-90db-9d51487f870a.png)

Any other item works as expected. Perhaps the title could be "how to remove items?".

**Comment by dreamerkumar** [comment]
Hi Staminna,

At this time it only works for a parent level item. The problem with child level items is that they are linked to individual parent item. Since dashboard pages are not in the context of a parent item, you can't load the child items in the dashboard. 

I had planned on creating dashboards at the item level where you could add widgets for child items. But I didn't get around to it. 

If you need to make it work, you will have to hard code parent ids in the requests that are made to retrieve the data for the child items.

**Comment by staminna** [comment]
so, to close this one, how do I find the parent id's and which file should I map them to?

**Comment by dreamerkumar** [comment]
You should have a parent id to get to the child items in the first place, right?
The way parent and child functionality works is that for each parent row (with its id), there can be a list of child items that can be added as reference. 
In the normal crud flow, the parent id is passed to the child crud pages. This makes it easy to pull the parent id from the route and pass it along while saving the child items.
On a dashboard, you cannot just start with child items. You should have a way to choose a parent item first. 
One implementation: Create a dropdown to select a parent item from the list. Then pass the id of the selected item, when you save child items.
Another implementation: First create a parent item. Use the id of the created parent item to then save the child items.

**Comment by staminna** [comment]
The dashboard does not seem to generate any files, and I couldn't find way to get a array of all parent id's.
I am using Microsoft Outlook's calendar view instead.
For now, to close this one, how do I deactivate the dashboard from the main menu?

**Comment by staminna** [comment]
I added ng-hide="$first" on the template file and it worked
