### ISSUE TITLE
User login and forgotten password.

### ISSUE THREAD

**Issue by staminna** [dreamerkumar/bizsitegenie#2]
Hi dreamerkumar. 

Password recovery doesn't seem to work on Mac OS and Ubuntu 12.04 with error code 500.

`POST http://localhost:3000/auth/forgot Failed to load resource: the server responded with  a status of 500 (Internal Server Error)
`

Thanks.

**Comment by dreamerkumar** [comment]
Hey there staminna,

Oops. I never got around to test the forgot password stuff myself. It was ported over as it is from the original mean.js framework. I feel pretty confident that it should work since that framework was in a stable state when I had forked it. I am guessing this might have to do with the environment setup you would need to send emails.

**Comment by staminna** [comment]
It's using https://nodemailer.com/ version 1.x
1. Find the file users.password.server.controller.js
nodemailer.createTransport(config.mailer.options) wasn't set anywhere.

```

var transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: 'sender@gmail.com',
        pass: 'password'
    }
```

Setting this up sent the email. Perhaps I could make a form for the admin to set this up somewhere though I have tendinitis on both arms and right hand so I can't promise.

**Comment by dreamerkumar** [comment]
This is very useful. Thanks for figuring this out!

I hope you get better. I myself have seen the doc five times already this year for carpal tunnel like syndrome. I guess it comes with the trade.

**Comment by staminna** [comment]
Thanks. Outgoing connections on port 465 must be open on the server.
I do massage very often and make stretches. There are many helpful videos on youtube. It's a great resource for this too.
